const types = {
  ADD_TODO: 'todo/add',
  DELETE_TODO: 'todo/delete',
  COMPLETED_TODO: 'todo/completed',

  GET_TODOS_REQUEST: 'GET_TODOS_REQUEST',
  GET_TODOS_SUCCESS: 'GET_TODOS_SUCCESS',
  GET_TODOS_FAILURE: 'GET_TODOS_FAILURE',

  ADD_TODOS_REQUEST: 'ADD_TODOS_REQUEST',
  ADD_TODOS_SUCCESS: 'ADD_TODOS_SUCCESS',
  ADD_TODOS_FAILURE: 'ADD_TODOS_FAILURE',

  DELETE_TODOS_REQUEST: 'DELETE_TODOS_REQUEST',
  DELETE_TODOS_SUCCESS: 'DELETE_TODOS_SUCCESS',
  DELETE_TODOS_FAILURE: 'DELETE_TODOS_FAILURE',

  COMPLETED_TODOS_REQUEST: 'COMPLETED_TODOS_REQUEST',
  COMPLETED_TODOS_SUCCESS: 'COMPLETED_TODOS_SUCCESS',
  COMPLETED_TODOS_FAILURE: 'COMPLETED_TODOS_FAILURE',
};

export default types;
